#! /bin/sh

sxhkd &
panel &

bspc config border_width  3
bspc config window_gap   24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config normal_border_color   '#729abd'
bspc config active_border_color   '#aa421b'
bspc config focused_border_color  '#aa421b'

bspc monitor -d term web game media misc

bspc rule -a Gimp desktop=media state=floating follow=on
bspc rule -a MPlayer desktop=media state=floating follow=on
bspc rule -a Jumanji desktop=web follow=on
bspc rule -a Firefox desktop=web follow=on
bspc rule -a Steam.exe desktop=game state=floating
