#! /bin/sh

getXresColor() {
    echo -n "$( xrdb -query | grep "\*$1:" | grep -oE "#[a-zA-Z0-9]{6}" )";
}

sxhkd -m -1 &
panel &

bspc config border_width   1
bspc config window_gap     8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config normal_border_color   "$(getXresColor background)"
bspc config active_border_color   "$(getXresColor color1)"
bspc config focused_border_color  "$(getXresColor color2)"

bspc monitor -d Web Chat Code Media Game Misc

bspc rule -a Firefox desktop=Web follow=on
bspc rule -a chromium desktop=Web follow=on
bspc rule -a 'Pale moon' desktop=Web follow=on

bspc rule -a URxvt:mutt desktop=Chat
bspc rule -a Skype desktop=Chat

bspc rule -a Gimp desktop=Media state=floating follow=on
bspc rule -a MPlayer desktop=Media state=floating follow=on
bspc rule -a Ario desktop=Media state=floating follow=on

bspc rule -a Steam desktop=Game
bspc rule -a Wine:Steam.exe desktop=Game
bspc rule -a dota2 desktop=Game
bspc rule -a wesnoth desktop=Game state=monocle
bspc rule -a Wine:explorer.exe desktop=Game
bspc rule -a nwn2main.exe desktop=Game state=floating

bspc rule -a Transmission-gtk desktop=Misc
